In [9]:
import numpy as np
from numpy import linalg as LA
A1=np.array([[0, 1, 0, 2, 3],[1, 0, 0, 3, 2],[3, -1, 0, 2, 3],[1, -1, 3, 0, 4],[-2, 1, -2, -2, 3]])
A2=np.array([[0, 2, 3, 3, 1],[2, 0, -1, 2, 3],[3, -1, 0, 5, 1],[3, 2, 5, 0, 2],[1, 3, 1, 2, 6]])
A1,A2

(array([[ 0,  1,  0,  2,  3],
        [ 1,  0,  0,  3,  2],
        [ 3, -1,  0,  2,  3],
        [ 1, -1,  3,  0,  4],
        [-2,  1, -2, -2,  3]]), array([[ 0,  2,  3,  3,  1],
        [ 2,  0, -1,  2,  3],
        [ 3, -1,  0,  5,  1],
        [ 3,  2,  5,  0,  2],
        [ 1,  3,  1,  2,  6]]))

In [35]:
w,v=LA.eig(A1)
v[:,1]
v[:,2]
v[:,3]
v[:,4]
v[:,5]

IndexError: index 5 is out of bounds for axis 1 with size 5

In [36]:
v[:,0]

array([ 0.03611597+0.37390458j,  0.15404221+0.36655165j,
        0.07387832+0.44905574j, -0.01656456+0.46501613j,
       -0.52647738+0.j        ])

In [37]:
w2,e=LA.eig(A2)
e[:,0]

array([0.3731337 , 0.31438582, 0.37399567, 0.47727298, 0.62790966])

In [43]:
e[:,4]

array([-0.15859057,  0.39411431,  0.66985833, -0.60761426, -0.0402203 ])

In [11]:
L=np.array([[3,-1,-1,0,-1,0],[-1,3,0,-1,0,-1],[-1,0,2,0,-1,0],[0,-1,0,2,0,-1],[-1,0,-1,0,2,0],[0,-1,0,-1,0,2]])
L

array([[ 3, -1, -1,  0, -1,  0],
       [-1,  3,  0, -1,  0, -1],
       [-1,  0,  2,  0, -1,  0],
       [ 0, -1,  0,  2,  0, -1],
       [-1,  0, -1,  0,  2,  0],
       [ 0, -1,  0, -1,  0,  2]])

In [13]:
wl,_=LA.eig(L)
wl

array([ 4.56155281e+00, -3.18975359e-16,  4.38447187e-01,  3.00000000e+00,
        3.00000000e+00,  3.00000000e+00])

In [17]:
L1=np.array([[2,-1,-1,0],[-1,1,-0,0],[-1,0,2,-1],[0,0,-1,1]])
L1

array([[ 2, -1, -1,  0],
       [-1,  1,  0,  0],
       [-1,  0,  2, -1],
       [ 0,  0, -1,  1]])

In [18]:
L3=np.array([[3,0,-1,-1,-1],[0,2,0,-1,-1],[-1,0,2,-1,0],[-1,-1,-1,3,0],[-1,-1,0,0,2]])
L3

array([[ 3,  0, -1, -1, -1],
       [ 0,  2,  0, -1, -1],
       [-1,  0,  2, -1,  0],
       [-1, -1, -1,  3,  0],
       [-1, -1,  0,  0,  2]])

In [20]:
L5=np.array([[2,0,-1,-1,0],[0,1,0,0,-1],[-1,0,2,-1,0],[-1,0,-1,2,0],[0,-1,0,0,1]])
L5

array([[ 2,  0, -1, -1,  0],
       [ 0,  1,  0,  0, -1],
       [-1,  0,  2, -1,  0],
       [-1,  0, -1,  2,  0],
       [ 0, -1,  0,  0,  1]])

In [23]:
a1,_=LA.eig(L1)
a1

array([3.41421356e+00, 2.00000000e+00, 3.47490713e-17, 5.85786438e-01])

In [24]:
a3,_=LA.eig(L3)
a3

array([-1.33226763e-15,  4.61803399e+00,  3.61803399e+00,  2.38196601e+00,
        1.38196601e+00])

In [25]:
a5,_=LA.eig(L5)
a5

array([ 3.00000000e+00, -2.22044605e-16,  1.11022302e-16,  2.00000000e+00,
        3.00000000e+00])